language: ruby
rvm:
- 2.4.1
script:
- "./_tests/travis-checks --quick"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
# Separate deployments
## - production
- provider: s3
  access_key_id: AKIAIRWAFHZDDWJ37X5A
  secret_access_key:
    secure: BlXQIyq/lHCHPGX5YUasTGWHkoL32lZHYG/n1yLBjniht2AKPWBnbQ+oWLJt2d28xZksXaDYQ02rh8lWted0SKhqYUN6dcmrXu8rVwcqpqgihUZsC1yqO4qGZ2qGkeQ2X0+HSKIBJ5VUKrMJiS3YK+N/W00/f9FatrSGvr8HBKSWpKpDiHq7z5kx/ab5Aae0hGyN1Ux6I7jTkYDI6oi9gQFJgv4oMKUt11SVMqnBNXoeOvDnIIkJqSf0hKuSZpeEDoX1FDlEaC/NR11ASlPj1ev+mxuNi1S1WTYFka7tB7piD9TQTv0PxjU+t4+TaH9jkd35eGUW1VeKPrdBtsK2TnCM6zYuM7/4U2i/7ZHf4bRVG8UkL+h32K25b24SQIyJddAzvrz8cM2/TLpqid+xdvay2Ax5T3acsxQhBq+vXVwohhl2q3fu9o6o6Bh8SGnn7XSK3JxE9Z3e8Uqg9JV3Pmgz8VyeYCwjuaV5lyabujQAn6sX8rw0RQ2A35bvQjAkNDiLUsmmOQBuRnnmS6fxeYDWf1D/h+6V0TWqPFQLTNBCjYt7WBDyTAU6i71c8ZDSay2CqVca0djxzXJHuqys5q4gRqXpLkuOiJUJMR8s5NhgQAI6bSCkgsJ/EcJqpSIwI72W+NgBb0I31KeREJXO5UlNmTa7RBFSX02KE23ut/E=
  bucket: www-measurementlab-net
  skip_cleanup: true
  local_dir: _site
  on:
    repo: m-lab/m-lab.github.io
    tags: true
## - staging
- provider: script
  script: scp -i _deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    -rp _site/* travis@35.208.41.230:website-staging/ && ssh -i _deploy_key -o UserKnownHostsFile=/dev/null
    -o StrictHostKeyChecking=no travis@35.208.41.230 'sudo cp -r website-staging/*
    /var/www/html/ && rm -rf website-staging/*'
  on:
    repo: m-lab/m-lab.github.io
    all_branches: true
    condition: "$TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push"
## - sandbox
- provider: script
  skip_cleanup: true
  script: scp -i _deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    -rp _site/* travis@35.208.229.232:website-sandbox/ && ssh -i _deploy_key -o UserKnownHostsFile=/dev/null
    -o StrictHostKeyChecking=no travis@35.208.229.232 'sudo cp -r website-sandbox/*
    /var/www/html/ && rm -rf website-sandbox/*'
  on:
    repo: m-lab/m-lab.github.io
    all_branches: true
    condition: "$TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push"
before_install:
# unencrypt the appropriate deploy key
## - production
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then openssl aes-256-cbc -K $encrypted_69b240b11ca3_key
  -iv $encrypted_69b240b11ca3_iv -in _cf_s3_invalidator.yml.enc -out _cf_s3_invalidator.yml
  -d; fi
## - staging
- if [ "$TRAVIS_BRANCH == master" ] && [ "$TRAVIS_EVENT_TYPE == push" ]; then openssl aes-256-cbc -K $encrypted_24201bc0bc50_key -iv $encrypted_24201bc0bc50_iv
  -in _staging_deploy_key.enc -out _deploy_key -d && eval "$(ssh-agent -s)" && chmod 600 _deploy_key && ssh-add _deploy_key; fi
## - sandbox
- if [ "$TRAVIS_BRANCH" == "sandbox-*" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then openssl aes-256-cbc -K $encrypted_24201bc0bc50_key -iv $encrypted_24201bc0bc50_iv
  -in _sandbox_deploy_key.enc -out _deploy_key -d && eval "$(ssh-agent -s)" && chmod 600 _deploy_key && ssh-add _deploy_key; fi
after_deploy: if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false"
  ] && [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then cf-s3-inv || travis_terminate 1; fi
