dist: xenial
language: ruby
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - NODE_VERSION=v10.17.0

script:
- set -e
- "$TRAVIS_BUILD_DIR/travis/install_gcloud.sh"
- sudo apt-get install -y python3-pip
- sudo python3 -m pip install --upgrade setuptools pip
- sudo python3 -m pip install jupyter nbconvert
# NOTE: generate-schema-docs uses templates from most recent v* tagged release:
#   https://github.com/m-lab/etl/tree/master/schema/descriptions
#
# The docker image is versioned using the same v* pattern as the release.
# (the prod-v* patterns are for parser deployments).
#
# You can find the latest tags in:
#   https://hub.docker.com/repository/docker/measurementlab/generate-schema-docs/tags
- docker run -v $PWD:/workspace -w /workspace
    -it measurementlab/generate-schema-docs:v0.1.0 -doc.output _includes
- nvm install $NODE_VERSION
- npm install -g firebase-tools
- "./_tests/travis-checks --quick"

deploy:
# Separate deployments to various places based on branch and push type
## - sandbox
- provider: script
  skip_cleanup: true
  script: "$TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_sandbox
    && gsutil cp -r $TRAVIS_BUILD_DIR/_site/* gs://website.mlab-sandbox.measurementlab.net/"
  on:
    repo: m-lab/website
    all_branches: true
    condition: "$TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push"

## - staging
- provider: script
  skip_cleanup: true
  script: "$TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_staging
    && gsutil cp -r $TRAVIS_BUILD_DIR/_site/* gs://website.mlab-staging.measurementlab.net/"
  on:
    repo: m-lab/website
    all_branches: true
    condition: "$TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push"

## - production
- provider: script
  skip_cleanup: true
  script: "firebase use mlab-oti && firebase deploy --only hosting --token $FIREBASE_TOKEN"
  on:
    repo: m-lab/website
    tags: true
