language: node_js
node_js:
  - 4.2
before_install:
# execute commands before dependencies can be installed
  - rvm install 2.1  
  - npm install -g grunt-cli
install:
# install dependencies
  - bundle install
  - npm install
script:
  - grunt test
branches:
  only:
  - master
  - gh-pages
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
