dist: xenial
language: ruby
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- set -e
- "$TRAVIS_BUILD_DIR/travis/install_gcloud.sh"
- sudo apt-get install -y python3-pip
- sudo python3 -m pip install --upgrade setuptools pip
- sudo python3 -m pip install jupyter nbconvert
- "./_tests/travis-checks --quick"
deploy:
- provider: firebase
  token: 
    secure: Z3Gksu2LnrpVbk+/ZwHY4vgfjsKy36HB1hRllOBmNJTxf4KBT52mDLWrHfxGTyDbi/7kxL83bIcfyJl0VhdT3iUAzGBnIGYEN7MobbCaXEDqpSgYHn7qIPfilYHeb9ddTHuDNNVIqSYVvTcKBQbY1OqAiyF9vQOsKdRoNYJ8eiKJWirlm8w/AFwDSiuLQc+C7kirJM90eAh+23ojuC/jejXqpBfE7Kc0v1ejIjg7eM5F4GuJeH+2Sujy8rym0nWhd7MUGGdDiSuVsHTOQLjeuW4hk5MBcp1p1o4L9AWJuAKLIgJ/VIixcx0+Ol7wG+wzQ22rk3LI82q51DW7xPmA0AxQcR1CHlVi8JF5EM149Cbclmg0MJkBgZireN2ydv5zW91/YfK6jvrlULSqDG0dubnfX3RKRjFtjB1bkjrmb1E5Uujhvg9bSn8lHhh6ODdZvyKr4+R3IztkTd0ppJIKLmv3i4X5fw4PV3IKLxylp5XvVijfaenRIVZv3GJ6o0Xkx6z8u8EtJwYBbc//Q5qVN061ShRPMEpynXzENa0IuZL0DDQa6A2jXKd4cS9IcktaxRXsgTuyvls8KvoJOCrbw4pAdTFfKGnFZT83y7IJT+8EVXtBO2j9wHMSv76otU0goAk2vquYjPczBdorRc8sMfargI3vQxD+bTjqMi75pFk=
  message: firebase test deploy
  on:
    repo: m-lab/website
    all_branches: true
    condition: "$TRAVIS_BRANCH == deploy-firebase && $TRAVIS_EVENT_TYPE == push"
- provider: script
  skip_cleanup: true
  script: "$TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_sandbox
    && gsutil cp -r $TRAVIS_BUILD_DIR/_site/* gs://website.mlab-sandbox.measurementlab.net/"
  on:
    repo: m-lab/website
    all_branches: true
    condition: "$TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push"
- provider: script
  skip_cleanup: true
  script: "$TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_staging
    && gsutil cp -r $TRAVIS_BUILD_DIR/_site/* gs://website.mlab-staging.measurementlab.net/"
  on:
    repo: m-lab/website
    all_branches: true
    condition: "$TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push"
- provider: script
  script: "$TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_oti
    && gsutil cp -r $TRAVIS_BUILD_DIR/_site/* gs://website.mlab-oti.measurementlab.net/"
  skip_cleanup: true
  on:
    repo: m-lab/website
    tags: true
