# Site settings
title: M-Lab
email: support@measurementlab.net
baseurl: ""
excerpt_separator: <!--more-->

# Build settings
permalink: "/blog/:title/"
sass:
  sass_dir: _sass
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - deploy
  - jekyll_frontmatter_tests-0.0.6
  - node_modules
  - gruntfile.js
  - package.json

# Gems
gems: ['jekyll-paginate', 'jekyll-feed']
paginate: 1
paginate_path: "/blog/page/:num"

# HTML Compression settings
compress_html:
  clippings: [ ]
  blanklines: false
  profile: false
