# Site settings
title: Measurement Lab
email: support@measurementlab.net
description: "M-Lab provides the largest collection of open Internet performance data on the planet. As a consortium of research, industry, and public interest partners, M-Lab is dedicated to providing an ecosystem for the open, verifiable measurement of global network performance. Real science requires verifiable processes, and M-Lab welcomes scientific collaboration and scrutiny. This is why all of the data collected by M-Lab's global measurement platform is made openly available, and all of the measurement tools hosted by M-Lab are open source. Anyone with the time and skill can review and improve the underlying methodologies and assumptions on which M-Lab's platform, tools, and data rely. Transparency and review are key to good science, and good science is key to good measurement."
encoding: "utf-8"
baseurl: ""

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title
category_dir: /blog/category
paginate: 10
paginate_path: "blog/page-:num"